service: ae-data-platform

useDotenv: true

configValidationMode: off

provider:
  name: scaleway

  # Scaleway region for the deploy
  scwRegion: fr-par

  # Scaleway organization ID
  scwProject: ${env:SCW_ACCESS_KEY_ID}
  scwToken: ${env:SCW_SECRET_ACCESS_KEY}

plugins:
  - serverless-scaleway-functions

# Include/exclude directories
package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"

custom:
  containers:
    ae-data-platform-processing:
      registryImage: ${env:SCW_REGISTRY}/ae-data-processing:latest
      minScale: 0
      maxScale: 1
      memoryLimit: 256
      port: 8080
      timeout: 100s
