service: ae-data-platform

useDotenv: true

configValidationMode: off

provider:
  name: scaleway

  # Scaleway region for the deploy
  scwRegion: fr-par

  # Scaleway organization ID
  scwProject: ${env:SCW_PROJECT}
  scwToken: ${env:SCW_TOKEN}

plugins:
  - serverless-scaleway-functions

# Include/exclude directories
package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"

custom:
  containers:
    ae-data-platform-processing:
      registryImage: ${env:SCW_REGISTRY}/ae-data-processing:latest
      minScale: 0
      maxScale: 1
      memoryLimit: 256
      cpuLimit: 140
      port: 8080
      timeout: 10s
      secret:
        DATABASE_URL: ${env:DATABASE_URL}
        DATABASE_NAME: ${env:DATABASE_NAME}
        S3_ENDPOINT: ${env:S3_ENDPOINT}
        S3_BUCKET: ${env:S3_BUCKET}
        S3_ID: ${env:S3_ID}
        S3_SECRET: ${env:S3_SECRET}

